# Максимальное количество подключений с одного IP
max-connections-per-ip: 5

# Время (в минутах) для отображения статистики
stats-time: 5

# Интервал очистки старых записей (в минутах)
cleanup-interval: 5